//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class GemID
{
	private object species
	{
		get;
		set;
	}

	private object shape
	{
		get;
		set;
	}

	private object cut
	{
		get;
		set;
	}

	private object clarity
	{
		get;
		set;
	}

	private object enhancement
	{
		get;
		set;
	}

	private object certificate
	{
		get;
		set;
	}

	private object mass
	{
		get;
		set;
	}

	private object origin
	{
		get;
		set;
	}

	private object photography
	{
		get;
		set;
	}

	private object dimension
	{
		get;
		set;
	}

	private object reference
	{
		get;
		set;
	}

	private object comments
	{
		get;
		set;
	}

	private object price
	{
		get;
		set;
	}

	private object pricePerCarat
	{
		get;
		set;
	}

	public virtual Status Status
	{
		get;
		set;
	}

}

