//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class User
{
	private object userID
	{
		get;
		set;
	}

	private object signupDate
	{
		get;
		set;
	}

	private object firstName
	{
		get;
		set;
	}

	private object lastName
	{
		get;
		set;
	}

	private object displayName
	{
		get;
		set;
	}

	private object email
	{
		get;
		set;
	}

	private object phone
	{
		get;
		set;
	}

	private object country
	{
		get;
		set;
	}

	private object address
	{
		get;
		set;
	}

	private object city
	{
		get;
		set;
	}

	public virtual Collection Collection
	{
		get;
		set;
	}

	public virtual IEnumerable<User> User
	{
		get;
		set;
	}

	public virtual Licence Licence
	{
		get;
		set;
	}

}

