//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class View
{
	private object name
	{
		get;
		set;
	}

	private object comments
	{
		get;
		set;
	}

	public virtual IEnumerable<GemID> GemID
	{
		get;
		set;
	}

}

